import fs from 'node:fs/promises';

import { decodeFirstCbor } from './cbor.js';

export const TYPE_HINTS = {
  1: 'integer',
  4: 'string',
  9: 'object/list',
  10: 'temperature',
  11: 'voltage',
  12: 'object/list',
  15: 'level/percent',
  18: 'timestamp/duration',
  100: 'identifier',
  102: 'power mode',
  103: 'enum',
  104: 'boolean/switch',
  105: 'enum/action',
  106: 'state enum',
  107: 'climate state',
  108: 'install state',
  109: 'location enum',
  110: 'language/enum',
  111: 'transfer state',
  114: 'state enum',
  117: 'state enum',
  119: 'timer state',
  202: 'error list',
  203: 'slot list',
  204: 'search result list',
  206: 'timer config'
};

const SENSITIVE_PARAMETERS = new Set(['CertThumb', 'Muid', 'SerialNr', 'UniqueID', 'UserName', 'Uuid']);

export function collectSettings(responseBuffers) {
  const settings = new Map();
  const topicLists = [];

  for (const buffer of responseBuffers) {
    const decoded = decodeFirstCbor(buffer);
    if (!decoded) continue;

    const candidate = Array.isArray(decoded) && decoded.length >= 2 ? decoded[1] : decoded;
    if (candidate && Array.isArray(candidate.tn)) topicLists.push(...candidate.tn.map(String));

    for (const topic of normalizeTopics(decoded)) {
      const topicName = String(topic.tn ?? '<unknown>');
      if (!settings.has(topicName)) settings.set(topicName, new Map());
      const bucket = settings.get(topicName);

      for (const parameter of Array.isArray(topic.parameters) ? topic.parameters : []) {
        if (!parameter || typeof parameter !== 'object') continue;
        const parameterName = String(parameter.pn ?? '<unknown>');
        bucket.set(parameterName, { ...(bucket.get(parameterName) || {}), ...parameter });
      }
    }
  }

  return { settings, topicLists: [...new Set(topicLists)] };
}

export async function writeSettingsFiles({ settings, topicLists }, { markdownPath, jsonPath, redact = true }) {
  if (markdownPath) {
    await fs.writeFile(markdownPath, renderMarkdown({ settings, topicLists, redact }), 'utf8');
  }
  if (jsonPath) {
    await fs.writeFile(jsonPath, JSON.stringify(toJson(settings, redact), null, 2) + '\n', 'utf8');
  }
}

export function renderMarkdown({ settings, topicLists, redact = true }) {
  const parameterCount = [...settings.values()].reduce((sum, params) => sum + params.size, 0);
  const lines = [
    '# Truma iNet X Live Settings',
    '',
    `Generated: \`${new Date().toISOString()}\``,
    '',
    'This file was generated by the live Node.js BLE probe.',
    redact ? 'Sensitive identity-like values are redacted.' : 'Sensitive values are included because redaction was disabled.',
    '',
    '## Summary',
    '',
    `- Topics with decoded parameters: ${settings.size}`,
    `- Decoded parameters: ${parameterCount}`
  ];

  if (topicLists.length) {
    lines.push('', '## Topic Lists Seen', '');
    for (const topic of topicLists) lines.push(`- ${topic}`);
  }

  for (const [topicName, params] of settings.entries()) {
    lines.push(
      '',
      `## ${topicName}`,
      '',
      '| Parameter | Type | Available | Permission | Value | Min | Max |',
      '| --- | --- | ---: | ---: | --- | ---: | ---: |'
    );
    for (const [parameterName, parameter] of params.entries()) {
      const row = [
        parameterName,
        typeText(parameter.type),
        valueToText(parameter.avail),
        valueToText(parameter.perm),
        valueToText(parameter.v, parameterName, redact),
        valueToText(parameter.min),
        valueToText(parameter.max)
      ];
      lines.push('| ' + row.map(tableEscape).join(' | ') + ' |');
    }
  }

  lines.push('');
  return lines.join('\n');
}

function normalizeTopics(value) {
  if (Array.isArray(value) && value.length >= 2 && value[1] && typeof value[1] === 'object') value = value[1];
  if (value && Array.isArray(value.topics)) return value.topics.filter((topic) => topic && typeof topic === 'object');
  if (value && typeof value === 'object' && value.tn && value.pn) return [{ tn: value.tn, parameters: [value] }];
  return [];
}

function toJson(settings, redact) {
  const output = {};
  for (const [topicName, params] of settings.entries()) {
    output[topicName] = {};
    for (const [parameterName, parameter] of params.entries()) {
      output[topicName][parameterName] = { ...parameter, v: maybeRedact(parameter.v, parameterName, redact) };
    }
  }
  return output;
}

function maybeRedact(value, parameterName, redact) {
  return redact && SENSITIVE_PARAMETERS.has(parameterName) ? '<redacted>' : value;
}

function typeText(value) {
  if (value === undefined || value === null) return '';
  const hint = TYPE_HINTS[value];
  return hint ? `${value} (${hint})` : String(value);
}

function valueToText(value, parameterName, redact = true) {
  value = maybeRedact(value, parameterName, redact);
  if (value === undefined || value === null) return '';
  if (Buffer.isBuffer(value)) return `0x${value.toString('hex')}`;
  if (Array.isArray(value)) return `[${value.map((item) => valueToText(item, undefined, redact)).join(', ')}]`;
  if (typeof value === 'object') {
    return `{${Object.entries(value).map(([key, item]) => `${key}: ${valueToText(item, undefined, redact)}`).join(', ')}}`;
  }
  return String(value);
}

function tableEscape(value) {
  return valueToText(value).replaceAll('|', '\\|').replaceAll('\n', ' ');
}
